import Head from "next/head";
import { ContactPageTable } from "~/components/individual-page/page-table/contact-page-table";
import { Breadcrumbs } from "~/components/breadcrumbs";
import { AddContact } from "~/components/create/create-contact";
import { Layout } from "~/components/layout";
import { useSession } from "next-auth/react";

export default function Contacts() {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>CRM / Contacts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-grow flex-col overflow-y-scroll p-5">
          {/* HEADER */}
          <div className="flex items-center justify-between">
            <div className="flex flex-col">
              <h1 className="text-xl font-bold">Contacts</h1>
              <span className="text-sm text-muted-foreground">
                View all of your contacts.
              </span>
            </div>
            {sessionData?.user.role.canCreateContact && <AddContact />}
          </div>
          <Breadcrumbs />
          <ContactPageTable />
        </div>
      </Layout>
    </>
  );
}
