import { UserAuthForm } from "~/components/user-auth-form";
import Head from "next/head";
import { Command } from "lucide-react";

export default function AuthenticationPage() {
  return (
    <>
      <Head>
        <title>CRM / Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center px-8 lg:grid lg:grid-cols-2 lg:px-0">
        <div className="relative hidden h-screen flex-col justify-between bg-slate-900 p-8 text-white lg:flex">
          <div className="flex items-center gap-2 text-lg font-medium">
            <Command />
            CRM
          </div>
          <div className="flex text-lg">Open-Source Contact Management</div>
        </div>
        <div className="lg:p-8">
          <div className="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
            <div className="flex flex-col space-y-2 text-center">
              <h1 className="text-2xl font-semibold tracking-tight">
                Login or create an account
              </h1>
              <p className="text-sm text-muted-foreground">
                Enter your email below to login or create your account
              </p>
            </div>
            <UserAuthForm />
            {/* <p className="px-8 text-center text-sm text-muted-foreground">
              By clicking continue, you agree to our{" "}
              <Link
                href="/terms"
                className="underline underline-offset-4 hover:text-primary"
              >
                Terms of Service
              </Link>{" "}
              and{" "}
              <Link
                href="/privacy"
                className="underline underline-offset-4 hover:text-primary"
              >
                Privacy Policy
              </Link>
              .
            </p> */}
          </div>
        </div>
      </div>
    </>
  );
}
