import Head from "next/head";

import { Sidebar } from "~/components/sidebar/sidebar-index";
import { Button } from "~/components/ui/button";
import { Plus } from "lucide-react";
import { CompanyPageTable } from "~/components/company-page-table";
import { Breadcrumbs } from "~/components/breadcrumbs";
import { ProjectPageTable } from "~/components/project-page-table";

export default function Projects() {
  return (
    <>
      <Head>
        <title>CRM / Projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen">
        <Sidebar />
        <div className="flex flex-grow flex-col p-5">
          {/* HEADER */}
          <div className="flex items-center justify-between">
            <div className="flex flex-col">
              <h1 className="text-xl font-bold">Projects</h1>
              <span className="text-sm text-muted-foreground">
                View all projects.
              </span>
            </div>
            <Button size={"sm"}>
              <Plus className="mr-1 h-4 w-4" />
              New
            </Button>
          </div>
          <Breadcrumbs />
          <ProjectPageTable />
        </div>
      </div>
    </>
  );
}
