import React from "react";
import Head from "next/head";

import { api } from "~/utils/api";
import { Sidebar } from "~/components/sidebar/sidebar-index";
import { usePathname } from "next/navigation";
import { Button } from "~/components/ui/button";
import { Plus } from "lucide-react";
import { CompanyPageTable } from "~/components/company-page-table";
import { Breadcrumbs } from "~/components/breadcrumbs";
import { AddCompany } from "~/components/add-company";

export default function Companies() {
  return (
    <>
      <Head>
        <title>CRM / Companies</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <Sidebar />
        <div className="flex flex-grow flex-col p-5">
          {/* HEADER */}
          <div className="flex items-center justify-between">
            <div className="flex flex-col">
              <h1 className="text-xl font-bold">Companies</h1>
              <span className="text-sm text-muted-foreground">
                View all companies.
              </span>
            </div>
            <AddCompany />
          </div>
          <Breadcrumbs />
          <CompanyPageTable />
        </div>
      </div>
    </>
  );
}
